kind: ENC[AES256_GCM,data:1P9eLonG,iv:sZnRdtXzDyEwBuAkiEKghHbc7LgH9tjyPyHf/+7dpPc=,tag:MVKHebixVcCZrmqYpXKlyw==,type:str]
ansible_user: ENC[AES256_GCM,data:RlpUxdXYGLLdNQ==,iv:sJtBASj0KxVpNWPVkhUALtys+WEzHICdK7ui4k0OGIc=,tag:SQ/JhDa8PXoceHECqRmEtg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GtJM0E+xanCm,iv:BRKNcbP4wf0/+o4lB+7g3ToYFPXQw8vgN1zOAde7fYo=,tag:KoG4lxNFsy94TKIR2msMZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vlzp0r5jnuzkpy7a6y3hp0swft4fz2qgn9lep85lu3v5r328z5yq2epm3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId0RNOWZLMFV6ZDhJc0tF
            d2xySnZkSTBsWnJLNXhLY3RiSVZLaTdCc1NjCkU2MmQ0OG5ZMm5jcDRyREN0YTRn
            aFdGdGlxWnpNbEozNDZVbk8vNUFNT2sKLS0tIGpOb0QrNXlVUTg1RVAzZ05sSUR5
            TCtsVE9Oa29NRTAvVXlqYWxEbVBoMkUKE/hqGGh+sWk+820ZAEOpBkibDua26fWV
            V9Bw7C5KASmli65FK+LpfhISvlNsBnGFSvXU3XL6ycKoBgMS7bAYUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-06T00:52:05Z"
    mac: ENC[AES256_GCM,data:kGTFq/eP34RG35u/0sNMds8puwu/dQoChhhi8RMGhceeZVLbGgqEUu20ynSnOT1n4DraNy992po3iMVi+cOi3+OmelAr5r0WOc755yYLU27lPZVB+YRAF3QXieLzMBwlTKba5bR7JQKP1istgk/DBvF0J/8X9P6EaH10qHAsFzk=,iv:LJbUGC+rM4Un9wg3nDz1J0aFzc1zDB/bkuUfh27LCZ0=,tag:28EvqPmBgdnXno/a2bnLJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
