kind: ENC[AES256_GCM,data:VlmR6xxt,iv:EBXXlm1etTD9iS/okROUlV2fKayjaJHGalXFTWOeXMI=,tag:Yb9vqkPIYBxZO0PdPyZ1AA==,type:str]
ansible_user: ENC[AES256_GCM,data:jwhk3pSHaPBHWA==,iv:ziC7ufUo7t93seFoqcPnqpeMG5BvonSWE1gkGrC8xC4=,tag:ZK81sKwWw5HNfxMYhxGUtg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:00YVPUBkEtKo,iv:xEXpoEcXps9mz/6mGReJIMIChuNsjQHo9Wd4jWsz75g=,tag:J+lY3N6Oz99jn0Pf+x7rBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vlzp0r5jnuzkpy7a6y3hp0swft4fz2qgn9lep85lu3v5r328z5yq2epm3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYVA3SXBBSWtzTGdWeWJx
            d0ltcUVodmVtRFJHZDdncEpVaGc2V3RzSlI4Clh3bWJXODRqRjY5ZkV0VXErTjU4
            NXh6aEFsWDRTQkJMWGdpaURCQlVMbk0KLS0tIDBWVkdlZXRMSWVVeTcrblZmbFk2
            M1NQdDFHdG9GdUo5Q0dNS0pPS3h6blUK/WWbo1fN4WpCSXyw80NcvDG2iyw2jkpq
            K5894PocptHH6QsNNQ8Qa0vL6Yt52IHlWY2dWyhQ4gTP1CP4ZcIVyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-05T19:16:56Z"
    mac: ENC[AES256_GCM,data:qiwiaG4AShniRXCyaZjBBL+Jus33r25uCmtd6rXV/W4n5MTH5EXXlJ4387FVSrpWkbpsH+7SsIZxmVXMVyc20exMsy25QOaUCC2MlCBd0T5Y7b7SJCgMDjBOnwpwqSrhAo562dh9kQ6th++7AiUi542PzohSrDgGpAvkHXo/2sg=,iv:tl3Q6J+vfmg/GohaQwRj3ZqE7pYDA6MkQDvtVZMzz3o=,tag:FwikUQxnecU/hOFaB8k1iA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
