kind: ENC[AES256_GCM,data:kPxTPh4x,iv:zGJQdZoqFN9AC18hrZ/zYngrpnrE/cXZo53xecbMGVM=,tag:PhDTi5qdbUkS1fFR2QIRkg==,type:str]
ansible_user: ENC[AES256_GCM,data:G9eN1k/fgs/mvA==,iv:dw+mnMPvHSw8QNqOn41v810NN5GhSAMpznd34GUjvOY=,tag:H5J44D/wk/jEo0KQJxMwGA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Sj0cDaTkj70R,iv:oEHS+3BgDvMNXQusj9AJS22Iq7J7Mlp9KllMFH5zjfk=,tag:JuOmbl50bV6hek7VvjlJHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vlzp0r5jnuzkpy7a6y3hp0swft4fz2qgn9lep85lu3v5r328z5yq2epm3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMG5SaGl0RS9FOTgvYjdv
            ZmpzRkI3a1hIMHRJV2M4V0FsbEgzM0YzZ0FBCm1yNjlqblFIKzdIdUtUVkVmcXdj
            R2Jvc0R6cEtMcWFCakZDb0xrbk1yT00KLS0tIHQ1T3dVM2djcWtHQWdmM1NuVi9L
            Zi9pRFVEbkFDN2pqcjNkTlB6VC9qS2cKAo35dNdt8wrgumi3BFz/eARSFNtx4kkj
            D8QtjDPPHG8vtnkmli7c9ISKKmcfsIs+5dGZF11hYuxtElVUJUSkkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-06T03:28:34Z"
    mac: ENC[AES256_GCM,data:HmdtSApB4gj/c7qjbalvYlRzCBTdiJJZcXWXsFTkLQm0/JhhsC3wbHkju6vBlOIWcwjEGi/x6CTltpVMUNCpgkdCSe4eJ3caXszclUrk+aAmzso44dsfPaqewAOKRnkewLKi2MyQ7E2pJa20UJ6l0qdb3bHadRCJROLwTSpCSTc=,iv:bDfGoeSVfRAnxlm7v4ix98cU4wppWrGUs8Ls0U8jLlY=,tag:8OISatRSoJAmJQsB2HD49w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
