apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:dy8LC9Gd4+OvWmszyDOnPrr3Nn7hrcz+EJnJUC2LCRHaFZJEHg==,iv:uieUsdwn/z0NHNCM5ecL7tHMK+YbEfxZTqc0BhrTB4w=,tag:jhhdLbz8/iA/cbtN+DTlEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vlzp0r5jnuzkpy7a6y3hp0swft4fz2qgn9lep85lu3v5r328z5yq2epm3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQTN2TGo4bW5GWmtkKzNY
            NUdxeUpsZ0diVXRjUWFObW1ZWDRCWUtBNnlJCkVLcVFrbk5DNWo3c3F5Y0FnSWtE
            aDlZalVDSFY3SEpOdXZtUlNjcmpXd1EKLS0tIHBFeisvL08vMCtsaUhURUZvZVcw
            NjF0blBqZmhsN2ZsazNFZ20vTlViRmMKgxIuqKxk18BCdT+8dmknt2tg5E2BTzm5
            VTWh1Pi8H0VYUngaE3UHA5LgP/BNUUvOJ/HzVesm2blP3VLGZsvmfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-06T00:52:05Z"
    mac: ENC[AES256_GCM,data:3slZ9bj9XoxwR0I4NVhfLdmtuhPaE3isML19KoKLBDnONlii6+SzJ1I8GbiwjAH6FUxbFNHIMWXO6SKLL/ibww0BhGAu6VoGuzVo9EsuSc+UbPCvjiR8haSS9gZEyIPWxOdH2bihx5UUncVitqFx/+aOfhzhuMuJv4JsfoP8crk=,iv:tBTs3iitkLd12fY2tEkiKAitFDFzFwQbDYvIRFpTRHQ=,tag:NfuGpLmWyeDeOeB14Ut/VA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
