---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.35.40.53"
  METALLB_LB_RANGE: "10.35.40.60-10.35.40.70"
  METALLB_K8S_GATEWAY_ADDR: "10.35.40.70"
  METALLB_INGRESS_ADDR: "10.35.40.69"
