apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hpRk6OgZvdLO7g==,iv:DzI9CX92G7TQWWDuCn+gf6MErqeOML5YLPhnk8bOPZU=,tag:pSbGZzvPuh51TKlgGNEr3A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:92Q13uBlVJEBEGpCGS9rGrpj2Wu2b8Q=,iv:gz/ru4DTL0CrFs8D43h/jkV3JKqw2KvM4eWcU5f0KgI=,tag:65yupnqEEx65wUHwKYnYlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vlzp0r5jnuzkpy7a6y3hp0swft4fz2qgn9lep85lu3v5r328z5yq2epm3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd0lWNUtoNHdVVUV1MnI4
            bFVVQjdDbHNPOG1lY0JDTW5CajN5TUZvU204CjBnY2hxTGZ4dFpzemhycUM2VDhU
            NkNTalkwT3ltSTVLQ1hWRVY3Um8rc1UKLS0tIGlDcEhHclpieU1uU3BmaTJDZk10
            dFExdFAxZXk3R2lNZUpUbENUTFNrNHMKhhtgLKzUi4ZY2T2t3WIyGgbzgsaES1Ml
            IxTGY9ZOpryJTKAIixk2q9tUAYnIej6LBV1mzodl+qJiXR1J2xum/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-04T00:39:44Z"
    mac: ENC[AES256_GCM,data:nIVnrAFPWNk+mpmQG7czP0XpSeI08nBsyCgmkgq9afyG4bV+UEGquqAKae9/i329pN1/81BhhX9zL6N/FIwwK5gdmKSo/nP5423o3i58RBJXkbbT8dTK+XSF3zbp41RkCJbUJKGe3bs6/njR/yPS3YXhhY8dvQjM8pdt8Z7Bd5Q=,iv:her/z+I/ItMUC6DaNXToEEFDlAJahOn4qNqRIEkIo9o=,tag:vwkq9eV3gt6Y4WsjLzfTxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
