apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7bCUmY+0bJkSdA==,iv:yk441J4fcd2mGHE5ykO11OTHq+xm5k6wdrOuijhVXis=,tag:NpIqV5dvBS29EqnMxQpwYQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:pZ+UU4+qSszFGhl+p3P7iHvdaI7cc3U=,iv:J8F8ezsBx0I9rA4Aqqez4MWa6qIJlfg1hHgXMy+bnzY=,tag:ypFFNC4iCNXS0vw8Q3So/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vlzp0r5jnuzkpy7a6y3hp0swft4fz2qgn9lep85lu3v5r328z5yq2epm3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNXoxNG9Uemp4aUtlVEt6
            TWVaWkpLK3lEaEcvV1lscGpIeVVyRHFVMW5rClhLK0ZTVkZia295T1doZCtLWEtU
            WWdic1hXQjdVTDlISjQyRXBvaXh4K1EKLS0tIDMvbHB0Nm54YXZqMUdsb1BkRis2
            bTFsR2NRdldZNDVKRml0cWYwaHVaUzgK/796YHmsv4hnZxxKmxfpSHMV2KjJLRyc
            PxaZbbgAm1/JkzSv4SBYaMluI0CfmVOG+OC0Jf2kJd4l4ARTz1iu5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T02:18:13Z"
    mac: ENC[AES256_GCM,data:LPpmcLRW83xIjfNOOgKLpnoV+XrVHhru82Vf/THJv4X699lEJpaps+bXrvGwzf8tnxOWhDGZgc2csuJZLyrhEb7vjwC0PTqZvuM/Y8M6FapqFMCujNYDQP4LOQROz13/2b2rZYqIVoUfNuLmuUadRiLsZ0Tp8KGbEfou6hWMIUo=,iv:2iVtIw0yeXkHgRh3sabtQrN0XiE1aN8flDxmYLhs9vY=,tag:SJcZrGP7T0n4IUFdVBQmYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
