apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+QYgImPyn9Srsg==,iv:2J1X3xviwfervGJKaoVc1BnrC/pj1ejzWKPD4vM3cqw=,tag:TpCyn4ZG1B36Twd9tT1w9w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KvqG3Nu/QypVm+tbjK14Swk+IpXz8TM=,iv:PEN8YgCERnGIq/rh6m3/d888ZkZetDP8Bp4w3f8fJwA=,tag:DFYd6858cjDTkhFnRNZpmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vlzp0r5jnuzkpy7a6y3hp0swft4fz2qgn9lep85lu3v5r328z5yq2epm3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdDh2UmN1Um9uSUQwQkg5
            WkFhRVZEQXZ4V3Q2U2NwQ0p0RUQ5TmJMb21BCklwSG5sa1c4WmZFTTRKZmdrWExC
            TWFtclROMFVQalJNV3JUbmhObjg4SUUKLS0tIFR0K3hGeXp5emRvaW11SEM1VTNm
            cC9WRmFULzhMdysyUy9jdkFienoxWWsKrYlta1gxlVsiFwj1ir5iyMk2LSPMcC6J
            N9KuVliFRLqeLbIoGUcSp9IKs2qGJb5IpJQDWxx6OlHH3Jm8Geo6Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-06T00:52:05Z"
    mac: ENC[AES256_GCM,data:WUYEIkJlomhiuzoFasCgx5PBqOoYaN03fncBHcFkzgf5uzSpJqgvyEt1fA/VzwVzcskIYaU/nyDxJMaTigVr/fjGVZKly27yk6Mhmek5GjrhNEYLu9hkC0vvrmYzFThXeT7bwbmtJRmP0OOeVPAE475WDarmvG8YOvgyr3UqPeI=,iv:1zKWrY2sHEvS+9eO5wDKdKkhHwkcvPDec3KzUcMypGY=,tag:s6V1MOxo5WXxcaKwbOnQsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
